version: '3'

services:
  dblog:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER:'plivocfg'
      - POSTGRES_DB:'plivo_cloud_logs'
    ports:
      - '5433:5433'
  dbcfg:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER:'plivocfg'
      - POSTGRES_DB:'plivo_cloud'
    ports:
      - '5432:5432'
  redis:
    image: redis
  cache:
    image: memcached
  apiservice:
    build: .
    depends_on:
      - dbcfg
      - dblog
      - cache
      - redis

